name: media-stack
services:
  # To use/enable VPN, Run this compose file with --profile=vpn.
  vpn:
    ## Read https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers for details on configuring VPN for your service provider.
    profiles: ["vpn"]
    container_name: vpn
    image: qmcgaw/gluetun:v3.38.0
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom # Valid values: nordvpn, expressvpn, protonvpn, surfshark or custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=20.195.15.183                                               
      - VPN_ENDPOINT_PORT=51820                                               
      - WIREGUARD_PUBLIC_KEY=LENyiu0kySvPXcgdiX90gg6nTeFEDDlPxwKkhUVJtyw=     
      - WIREGUARD_PRIVATE_KEY=<redacted>    
      - WIREGUARD_PRESHARED_KEY=<redacted>
      - WIREGUARD_ADDRESSES=10.27.101.3/24
      - FIREWALL_VPN_INPUT_PORTS=6881                                
    networks:
      - mynetwork

    # # Uncomment below when using VPN in an LXC container
    # # Make sure to mount /dev/net/tun and /dev/net from underlaying host into your LXC.
    # devices:
    #   - /dev/net/tun:/dev/net/tun
      
    # Uncomment/enable below ports if VPN is used/enabled
    # ports:
    #   # qbittorrent ports
    #   - 5080:5080
    #   - 6881:6881
    #   - 6881:6881/udp
    #   # prowlarr ports
    #   - 9696:9696
    restart: "unless-stopped"

  ## Default credentials of qBittorrent - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  qbittorrent:
    profiles: ["vpn", "no-vpn"]
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:4.6.7

    # Unomment below if vpn is enabled
    # depends_on:               # Uncomment this line if vpn is enabled
    #   - vpn                   # Uncomment this line if vpn is enabled

    # Comment below lines if VPN is enabled
    networks:               # Comment this line if vpn is enabled
      - mynetwork           # Comment this line if vpn is enabled

    # Unomment below line if vpn is enabled
    # network_mode: service:vpn

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/data/torrents

    ## Comment/Disable below ports if VPN is enabled
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  radarr:
    profiles: ["vpn", "no-vpn"]
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.16.3
    networks:
      - mynetwork   # Comment this line if VPN is enabled
    ## Uncomment below lines if VPN is enabled
      # mynetwork:
      #   ipv4_address: ${RADARR_STATIC_CONTAINER_IP} # It should be available IPv4 address in range of docker network `mynetwork` e.g. 172.20.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - starr:/data
    restart: "unless-stopped"

  sonarr:
    profiles: ["vpn", "no-vpn"]
    image: linuxserver/sonarr:4.0.11
    container_name: sonarr
    networks:
      - mynetwork   # Comment this line if VPN is enabled
    ## Uncomment below lines if VPN is enabled
      # mynetwork:
      #   ipv4_address: ${SONARR_STATIC_CONTAINER_IP} # It should be available IPv4 address in range of docker network `mynetwork` e.g. 172.20.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - starr:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    profiles: ["vpn", "no-vpn"]
    container_name: prowlarr
    image: linuxserver/prowlarr:1.28.2

    # Uncomment below if vpn is enabled
    # depends_on:               # Uncomment this line if vpn is enabled
    #   - vpn                   # Uncomment this line if vpn is enabled
    # network_mode: service:vpn # Uncomment this line if vpn is enabled

    networks:               # Comment this line if vpn is enabled
      - mynetwork           # Comment this line if vpn is enabled
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config

    # Comment below ports if VPN is enabled.
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    profiles: ["vpn", "no-vpn"]
    image: fallenbagel/jellyseerr:2.2.3
    container_name: jellyseerr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    profiles: ["vpn", "no-vpn"]
    image: linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - media:/data/media
    devices:
      - /dev/dri:/dev/dri # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

volumes:
  starr:
    driver: local
    driver_opts:
      type: none
      device: /mnt/starr
      o: bind
  media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/starr/media
      o: bind
  torrent-downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/starr/torrents
      o: bind
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:

networks:
  mynetwork:
    external: true
